import pytest
from selenium import webdriver

@pytest.fixture
def driver(request):
    wd = webdriver.Chrome()
    print(wd.capabilities)
    request.addfinalizer(wd.quit)
    return wd

#login example
def test_example(driver):
    driver.get("http://localhost:8080/litecart/admin/login.php")
    driver.find_element_by_name("username").send_keys("admin")
    driver.find_element_by_name("password").send_keys("admin")
    driver.find_element_by_name("login").click()
    driver.find_element_by_xpath("//li[@id='app-']/a/span[2]").click()
    driver.find_element_by_xpath("//li[@id='doc-template']/a/span").click()
    driver.find_element_by_xpath("//li[@id='doc-logotype']/a/span").click()
    driver.find_element_by_xpath("(.//*[normalize-space(text()) and normalize-space(.)='Logotype'])[1]/following::span[2]").click()
    driver.find_element_by_xpath("//li[@id='doc-product_groups']/a/span").click()
    driver.find_element_by_xpath("//li[@id='doc-option_groups']/a/span").click()
    driver.find_element_by_xpath("//li[@id='doc-manufacturers']/a/span").click()
    driver.find_element_by_xpath("//li[@id='doc-suppliers']/a/span").click()
    driver.find_element_by_xpath("//li[@id='doc-delivery_statuses']/a/span").click()
    driver.find_element_by_xpath("//li[@id='doc-sold_out_statuses']/a/span").click()
    driver.find_element_by_xpath("//li[@id='doc-quantity_units']/a/span").click()
    driver.find_element_by_xpath("//li[@id='doc-csv']/a/span").click()
    driver.find_element_by_xpath("(.//*[normalize-space(text()) and normalize-space(.)='CSV Import/Export'])[1]/following::span[2]").click()
    driver.find_element_by_xpath("(.//*[normalize-space(text()) and normalize-space(.)='Countries'])[1]/following::span[2]").click()
    driver.find_element_by_xpath("(.//*[normalize-space(text()) and normalize-space(.)='Currencies'])[1]/following::span[2]").click()
    driver.find_element_by_xpath("//li[@id='doc-csv']/a/span").click()
    driver.find_element_by_xpath("//li[@id='doc-newsletter']/a/span").click()
    driver.find_element_by_xpath("(.//*[normalize-space(text()) and normalize-space(.)='Newsletter'])[1]/following::span[2]").click()
    driver.find_element_by_xpath("(.//*[normalize-space(text()) and normalize-space(.)='Geo Zones'])[1]/following::span[2]").click()
    driver.find_element_by_xpath("//li[@id='doc-storage_encoding']/a/span").click()
    driver.find_element_by_xpath("(.//*[normalize-space(text()) and normalize-space(.)='Storage Encoding'])[1]/following::span[2]").click()
    driver.find_element_by_xpath("//li[@id='doc-customer']/a/span").click()
    driver.find_element_by_xpath("//li[@id='doc-shipping']/a/span").click()
    driver.find_element_by_xpath("//li[@id='doc-payment']/a/span").click()
    driver.find_element_by_xpath("//li[@id='doc-order_total']/a/span").click()
    driver.find_element_by_xpath("//li[@id='doc-order_success']/a/span").click()
    driver.find_element_by_xpath("//li[@id='doc-order_action']/a/span").click()
    driver.find_element_by_xpath("(.//*[normalize-space(text()) and normalize-space(.)='Order Action'])[1]/following::span[2]").click()
    driver.find_element_by_xpath("//li[@id='doc-order_statuses']/a/span").click()
    driver.find_element_by_xpath("(.//*[normalize-space(text()) and normalize-space(.)='Order Statuses'])[1]/following::span[2]").click()
    driver.find_element_by_xpath("(.//*[normalize-space(text()) and normalize-space(.)='Pages'])[1]/following::span[2]").click()
    driver.find_element_by_xpath("//li[@id='doc-most_sold_products']/a/span").click()
    driver.find_element_by_xpath("//li[@id='doc-most_shopping_customers']/a/span").click()
    driver.find_element_by_xpath("(.//*[normalize-space(text()) and normalize-space(.)='Most Shopping Customers'])[1]/following::span[2]").click()
    driver.find_element_by_xpath("//li[@id='doc-defaults']/a/span").click()
    driver.find_element_by_xpath("//li[@id='doc-general']/a/span").click()
    driver.find_element_by_xpath("//li[@id='doc-listings']/a/span").click()
    driver.find_element_by_xpath("//li[@id='doc-images']/a/span").click()
    driver.find_element_by_xpath("//li[@id='doc-checkout']/a/span").click()
    driver.find_element_by_xpath("//li[@id='doc-advanced']/a/span").click()
    driver.find_element_by_xpath("//li[@id='doc-security']/a/span").click()
    driver.find_element_by_xpath("(.//*[normalize-space(text()) and normalize-space(.)='Security'])[1]/following::span[2]").click()
    driver.find_element_by_xpath("(.//*[normalize-space(text()) and normalize-space(.)='Slides'])[1]/following::span[2]").click()
    driver.find_element_by_xpath("//li[@id='doc-tax_rates']/a/span").click()
    driver.find_element_by_xpath("(.//*[normalize-space(text()) and normalize-space(.)='Tax Rates'])[1]/following::span[2]").click()
    driver.find_element_by_xpath("//li[@id='doc-scan']/a/span").click()
    driver.find_element_by_xpath("//li[@id='doc-csv']/a/span").click()
    driver.find_element_by_xpath("(.//*[normalize-space(text()) and normalize-space(.)='CSV Import/Export'])[1]/following::span[2]").click()
    driver.find_element_by_xpath("(.//*[normalize-space(text()) and normalize-space(.)='Users'])[1]/following::span[2]").click()